# Simple Linear Regression

In [3]:
# Name : Sayyed Salik Sagheer Jawwad
# Class : 3B
# Roll No. 44

In [5]:
import pandas as pd

In [7]:
import os

In [9]:
os.getcwd()

'C:\\Users\\salik\\DSS Practical'

In [11]:
os.chdir("C:\\Users\\salik\\OneDrive\\Desktop")

In [76]:
df =  pd.read_csv('Salary.csv')

In [78]:
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [80]:
df.tail()

YearsExperience  Salary
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  35 non-null     float64
 1   Salary           35 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 692.0 bytes


In [84]:
df.describe()

YearsExperience         Salary
count        35.000000      35.000000
mean          6.308571   83945.600000
std           3.618610   32162.673003
min           1.100000   37731.000000
25%           3.450000   57019.000000
50%           5.300000   81363.000000
75%           9.250000  113223.500000
max          13.500000  139465.000000

In [86]:
df.shape

(35, 2)

In [88]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [90]:
#Assiging values in X & Y
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values



#X = df['YearsExperience']
#y = df['Salary']

In [92]:
A = "Ashish"

In [94]:
print(A)

Ashish


In [96]:
A[0]

'A'

In [98]:
A[4]

's'

In [100]:
A[1:3]

'sh'

In [102]:
A[1:4]

'shi'

In [107]:
print(X)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]
 [11.2]
 [11.5]
 [12.3]
 [12.9]
 [13.5]]


In [109]:
print(y)

[ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872
 127345 126756 128765 135675 139465]


In [111]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [113]:
#Splitting testdata into X_train,X_test,y_train,y_test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3,random_state=42) 

In [115]:
print(X_train)

[[12.9]
 [ 1.1]
 [ 2.2]
 [ 5.3]
 [ 9.6]
 [ 2.9]
 [ 4. ]
 [ 1.3]
 [ 1.5]
 [12.3]
 [ 2. ]
 [11.2]
 [ 8.2]
 [11.5]
 [ 3.9]
 [ 7.9]
 [ 5.9]
 [ 9. ]
 [ 3. ]
 [ 6.8]
 [13.5]
 [ 3.2]
 [ 4.5]
 [10.3]]


In [117]:
print(X_test)

[[ 9.5]
 [ 4.1]
 [ 8.7]
 [ 7.1]
 [ 4.9]
 [10.5]
 [ 6. ]
 [ 4. ]
 [ 3.2]
 [ 5.1]
 [ 3.7]]


In [119]:
print(y_train)

[135675  39343  39891  83088 112635  56642  55794  46205  37731 128765
  43525 127345 113812 126756  63218 101302  81363 105582  60150  91738
 139465  54445  61111 122391]


In [121]:
print (y_test)

[116969  57081 109431  98273  67938 121872  93940  56957  64445  66029
  57189]


In [123]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [125]:
#Assigning Coefficient (slope) to m
m = lr.coef_  

In [127]:
print("Coefficient  :" , m)

Coefficient  : [8555.33918938]


In [129]:
#Assigning Y-intercept to a
c = lr.intercept_

In [131]:
print("Intercept : ", c)

Intercept :  29602.07353482095


In [133]:
lr.score(X_test,y_test) * 100

91.71426108885098